### PR TITLE
Fix ticket 11528 (MSVS 2015 + boost::range: STL and Boost iterators)

### PR DESCRIPTION
**Pull request by morinmorin**

### CODE REVIEW

**Comment by pdimov** [comment]
This pull request has introduced an unfortunate circular dependency between Algorithm and Range. It would be good if we can fix this.

**Comment by morinmorin** [comment]
> This pull request has introduced an unfortunate circular dependency between Algorithm and Range. 

Why does Algorithm depend on Range? StringAlgo is the culprit?

> It would be good if we can fix this.

I think implementation of `min_element/max_element` would be easy (and we can mark it as `BOOST_CXX14_CONSTEXPR` as an enhancement), but this introduces duplication and divergence of the same function between Range and Algorithm...

**Comment by pdimov** [comment]
> Why does Algorithm depend on Range?

https://pdimov.github.io/boostdep-report/develop/algorithm.html#range

**Comment by morinmorin** [comment]
For the record, the dependency on Boost.Algorithm is now removed by #91.

@pdimov Sorry for not fixing the dependency issue. I made a fix, but forgot to submit PR.

**Pull request merged**
